name: Build packages

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package: [Base, Fluent, OpenMoji]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Build ${{ matrix.package }}
      run: dotnet pack -c:Release
      working-directory: ${{ matrix.package }}

    - name: Publish ${{ matrix.package }}
      uses: actions/upload-artifact@v4
      with:
        name: nuget-${{ matrix.package }}
        path: ${{ matrix.package }}/bin/Release/*.*nupkg
        retention-days: 5
